name: Audit & Correction Connexion
on:
  schedule:
    - cron: '0 2 * * *' # tous les jours à 2h UTC
  workflow_dispatch:
jobs:
  audit-login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Vérifier page login
        run: |
          curl -fsSL https://www.rcvo-crm-auto.com/login.html || exit 1
      - name: Corriger route si erreur
        run: |
          if [ $? -ne 0 ]; then
            sed -i 's/login_v2/login/g' public/login_v2.html
            git config user.name 'github-actions'
            git config user.email 'actions@github.com'
            git add public/login_v2.html
            git commit -m '🔧 Correction connexion: relocalisation login'
            git push
          fi
