name: Auto Commit Scaffold
on:
  workflow_dispatch:

jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
      - name: Commit scaffold files
        run: |
          git add backend/ frontend/ infrastructure/ .github/workflows/
          git commit -m "chore: add initial scaffold (backend, frontend, infra, CI/CD)" || echo "Rien à committer"
      - name: Push to main
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
