name: Auto-scaffold RCVo

on:
  push:
    branches:
      - main
    # adapte les chemins selon où se trouve ton frontend à scaffold­er
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  auto_scaffold:
    name: Auto-scaffold project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Generate scaffold
        run: |
          # remplace cette ligne par ta commande de génération de scaffold
          npx create-next-app frontend --typescript --eslint --src-dir --app

      - name: Commit scaffold
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add frontend
          git commit -m "chore: auto-scaffold" || echo "No changes to commit"

      - name: Push to main
        run: git push origin HEAD:main

      - name: Sync to S3 bucket
        if: ${{ github.ref == 'refs/heads/main' }}
        run: aws s3 sync frontend/out s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront distribution
        if: ${{ secrets.CLOUDFRONT_ID != '' }}
        uses: jakejarvis/cloudfront-invalidate-action@v2
        with:
          distribution-id: ${{ secrets.CLOUDFRONT_ID }}
          paths:          '/*'
