name: Auto-échafaudage RCVo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scaffold:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ASSISTANT_ROLE_ARN }}
          aws-region:      ${{ secrets.AWS_REGION }}

      - name: Générer le scaffold
        run: |
          mkdir -p backend frontend infrastructure
          # Exemple backend
          cat > backend/main.go << 'EOF'
          package main
          import "fmt"
          func main() { fmt.Println("Hello RCVo backend!") }
          EOF
          # Exemple frontend
          cat > frontend/index.html << 'EOF'
          <!DOCTYPE html>
          <html><head><meta charset="utf-8"><title>RCVo</title></head>
          <body><h1>Bienvenue sur RCVo</h1></body></html>
          EOF
          # Exemple infra
          cat > infrastructure/main.tf << 'EOF'
          terraform {
            required_providers {
              aws = { source = "hashicorp/aws" version = "~> 4.0" }
            }
          }
          provider "aws" { region = var.aws_region }
          resource "aws_s3_bucket" "rcvo_static" {
            bucket = "rcvo-static-site-\${random_id.id.hex}"
            acl    = "public-read"
          }
          EOF
          cat > infrastructure/versions.tf << 'EOF'
          terraform { required_version = ">= 1.5.0" }
          EOF

      - name: Commit des fichiers de scaffold
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "actions@github.com"
          git add backend frontend infrastructure
          git commit -m "chore: add initial scaffold RCVo" || echo "Rien à committer"

      - name: Push sur main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin HEAD:main

      - name: Synchronisation vers S3
        run: |
          aws s3 sync frontend s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidation CloudFront (optionnel)
        if: ${{ secrets.CLOUDFRONT_ID != '' }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_ID }} \
            --paths "/*"
