name: Auto-scaffold RCVo

on:
  push:
    branches:
      - main

jobs:
  échafaud:                      # l’ID du job doit être alphanumérique et sans accents
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Generate scaffold
        run: |
          # ici ton propre générateur, par exemple :
          npm install -g rcvo-scaffold-generator
          scaffold-rcvo

      - name: Commit scaffold changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add frontend/
          git commit -m "chore: auto-scaffold RCVo" || echo "No changes to commit"

      - name: Push to main
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Sync to S3 bucket
        run: |
          aws s3 sync frontend/ s3://${{ secrets.S3_BUCKET }} --delete

      - name: Invalidate CloudFront (optional)
        if: ${{ secrets.CLOUDFRONT_ID != '' }}
        uses: chetan/invalidate-cloudfront-action@v1
        with:
          distribution: ${{ secrets.CLOUDFRONT_ID }}
          paths: '/*'
