# .github/workflows/auto-scaffold.yml
name: Auto-échafaudage RCVo
on:
  push:
    branches: [ main ]

jobs:
  échafaud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configurer AWS (clés statiques)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Générer le scaffold
        run: |
          # ta commande pour générer le frontend / boilerplate
          npm ci
          npm run build:scaffold

      - name: Commit des fichiers de scaffold
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git diff --quiet || git commit -m "chore: mise à jour automatique du scaffold"

      - name: Push sur main
        run: git push origin HEAD:main

      - name: Synchroniser vers S3
        run: aws s3 sync frontend s3://${{ secrets.S3_BUCKET }} --delete

      - name: Invalidation CloudFront (optionnelle)
        if: ${{ secrets.CLOUDFRONT_ID != '' }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_ID }} \
            --paths "/*"
