name: Complete CI & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (sécurisé)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Détecter projet Node
        id: detect
        shell: bash
        run: |
          if [ -f package.json ]; then
            echo "has_node=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_node=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Installer dépendances (safe)
        if: ${{ steps.detect.outputs.has_node == 'true' }}
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci --no-audit --no-fund
          else
            npm i  --no-audit --no-fund
          fi

      - name: Build (si script existe)
        if: ${{ steps.detect.outputs.has_node == 'true' }}
        run: |
          if npm run | grep -q "^  build"; then
            npm run build --silent
          else
            echo "Pas de script build, on saute."
          fi

      - name: Archiver le build
        if: ${{ steps.detect.outputs.has_node == 'true' }}
        run: |
          if [ -d dist ]; then
            tar -czf build-artifact.tgz dist
          elif [ -d build ]; then
            tar -czf build-artifact.tgz build
          else
            echo "Aucun dossier dist/build, on saute."
          fi

      - name: Upload artifact
        if: ${{ steps.detect.outputs.has_node == 'true' && hashFiles('build-artifact.tgz') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build-artifact.tgz

  deploy-staging:
    name: Déploiement staging
    needs: build
    runs-on: ubuntu-latest

    steps:
      # --- Évaluer la présence des secrets DOCKER (sans les mettre dans l'expression du YAML)
      - name: Évaluer secrets Docker
        id: eval_docker
        env:
          DU: ${{ secrets.DOCKER_USERNAME }}
          DP: ${{ secrets.DOCKER_PASSWORD }}
          DI: ${{ secrets.DOCKER_IMAGE }}
        run: |
          if [ -n "${DU}" ] && [ -n "${DP}" ]; then
            echo "go=true"  >> "$GITHUB_OUTPUT"
            echo "image=${DI:-rcvo/app}" >> "$GITHUB_OUTPUT"
          else
            echo "go=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Log info
        run: |
          echo "Docker prêt ? ${{ steps.eval_docker.outputs.go }}"

      - name: Checkout
        if: ${{ steps.eval_docker.outputs.go == 'true' }}
        uses: actions/checkout@v4

      - name: Télécharger l’artifact
        if: ${{ steps.eval_docker.outputs.go == 'true' }}
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .

      - name: Docker login
        if: ${{ steps.eval_docker.outputs.go == 'true' }}
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker
        if: ${{ steps.eval_docker.outputs.go == 'true' }}
        env:
          IMAGE: ${{ steps.eval_docker.outputs.image }}
          TAG:   ${{ github.sha }}
        run: |
          docker build -t "$IMAGE:$TAG" .
          docker push "$IMAGE:$TAG"

      # --- Évaluer la présence des secrets SSH, puis conditionner la step SSH sur l'output
      - name: Évaluer secrets SSH
        id: eval_ssh
        env:
          SH: ${{ secrets.SSH_HOST }}
          SU: ${{ secrets.SSH_USER }}
          SK: ${{ secrets.SSH_KEY }}
        run: |
          if [ -n "${SH}" ] && [ -n "${SU}" ] && [ -n "${SK}" ]; then
            echo "go=true" >> "$GITHUB_OUTPUT"
          else
            echo "go=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Déploiement SSH (optionnel)
        if: ${{ steps.eval_ssh.outputs.go == 'true' && steps.eval_docker.outputs.go == 'true' }}
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Pull & restart avec tag ${{ github.sha }}"
            # docker pull/run … ou systemctl restart …

  deploy-production:
    name: Déploiement production (manuel)
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}  # manuel uniquement
    steps:
      - name: Garde
        run: echo "⚠️ Le déploiement production est manuel uniquement. Relance le workflow et sélectionne ce job."
