name: Complete CI & Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  audit-and-test:
    name: Audit & Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Rendre le script d’audit exécutable
        run: chmod +x audit_rcvo.sh

      - name: Audit & Tests
        run: ./audit_rcvo.sh

  deploy-staging:
    name: Déployer sur staging
    needs: audit-and-test
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      STAGING_HOST:    ${{ secrets.STAGING_HOST }}
      STAGING_USER:    ${{ secrets.STAGING_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Build & Push Docker
        run: |
          if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
            echo "❌ Le secret DOCKER_USERNAME ou DOCKER_PASSWORD est manquant."
            exit 1
          fi

          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t rcvo/staging:latest .
          docker push rcvo/staging:latest

      - name: Déployer sur le serveur de staging
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ env.STAGING_HOST }}
          username: ${{ env.STAGING_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            set -eux
            cd /opt/rcvo
            docker pull rcvo/staging:latest
            docker-compose down
            docker-compose up -d

  deploy-production:
    name: Déployer sur production
    needs: deploy-staging
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      PROD_HOST:       ${{ secrets.PROD_HOST }}
      PROD_USER:       ${{ secrets.PROD_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Build & Push Docker (prod)
        run: |
          if [ -z "$DOCKER_USERNAME" ] || [ -z "$DOCKER_PASSWORD" ]; then
            echo "❌ Le secret DOCKER_USERNAME ou DOCKER_PASSWORD est manquant."
            exit 1
          fi

          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker build -t rcvo/prod:${{ github.ref_name }} .
          docker push rcvo/prod:${{ github.ref_name }}

      - name: Déployer sur la production
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ env.PROD_HOST }}
          username: ${{ env.PROD_USER }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            set -eux
            cd /opt/rcvo
            docker pull rcvo/prod:${{ github.ref_name }}
            docker-compose down
            docker-compose up -d

      - name: Vérifier la production
        run: |
          chmod +x ci/verify_prod.sh
          ./ci/verify_prod.sh
