jobs:
  cost-optimization:
    name: Cost Optimization
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # --- PASSE DE DEBUG ---
      - name: Debug folder layout
        run: |
          echo "=== Racine du dépôt ==="
          ls -R .

      # --- VÉRIFICATION DU MODULE ---
      - name: Verify cost-optimizer module exists
        run: |
          if [ ! -d backend/terraform/modules/cost-optimizer ]; then
            echo "❌ Erreur : module cost-optimizer introuvable !"
            exit 1
          fi

      # --- SUITE DU PIPELINE ---
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Terraform Init & Apply
        run: |
          cd backend/terraform
          terraform init
          terraform apply -auto-approve

      - name: Cleanup unattached EBS volumes
        run: ... 

      - name: Release unused Elastic IPs
        run: ... 

      - name: Convert test ASG to Spot
        run: ...

    # éventuels autres jobs ou steps...
