name: Cost Optimization

on:
  schedule:
    - cron: '0 6 * * MON'   # tous les lundis à 8h CEST

jobs:
  cost-optimize:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run Terraform Apply (cost-optimizer)
        working-directory: backend/terraform/modules/cost-optimizer
        run: |
          terraform init -input=false
          terraform apply -auto-approve -var "private_subnet_id=${{ secrets.PRIVATE_SUBNET_ID }}"

      - name: Cleanup unattached EBS volumes
        run: |
          for vol in $(aws ec2 describe-volumes --filters Name=status,Values=available --query "Volumes[].VolumeId" --output text); do
            aws ec2 delete-volume --volume-id $vol || true
          done

      - name: Release unused Elastic IPs
        run: |
          for aip in $(aws ec2 describe-addresses --query "Addresses[?AssociationId==\`null\`].AllocationId" --output text); do
            aws ec2 release-address --allocation-id $aip || true
          done

      - name: Spot conversion for test ASG
        run: |
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name rcvo-test-asg \
            --mixed-instances-policy file://test-asg-spot-policy.json || true
