name: Cost Optimization (manual only)
on:
  workflow_dispatch:
    inputs:
      tf_dir:
        description: 'Chemin du code Terraform (ex: infra/cost-optimizer)'
        required: false
        default: 'infra/cost-optimizer'
jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow coût désactivé par défaut. Lance-le manuellement si besoin."
