name: Cost Optimization

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cost-optimization:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug folder layout
        run: |
          echo "=== Racine du dépôt ==="
          ls -R .

      - name: Verify cost-optimizer module exists
        run: |
          if [ ! -d backend/terraform/modules/cost-optimizer ]; then
            echo "❌ Erreur : module cost-optimizer introuvable !"
            exit 1
          fi

      # ← NOUVEAU : installer Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "latest"

      - name: Terraform Init
        working-directory: backend/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: backend/terraform
        run: terraform apply -auto-approve

      - name: Cleanup unattached EBS volumes
        run: |
          # votre script ici...
          echo "Cleaning unattached EBS volumes"

      - name: Release unused Elastic IPs
        run: |
          # votre script ici...
          echo "Releasing unused Elastic IPs"

      - name: Convert test ASG to Spot
        run: |
          # votre script ici...
          echo "Converting test ASG to Spot"
