# .github/workflows/deploy-to-s3.yml
name: Deploy to S3

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write   # nécessaire pour OIDC

jobs:
  deploy:
    name: Build & Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ASSISTANT_ROLE_ARN }}
          aws-region:    ${{ secrets.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        working-directory: ./frontend
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Sync build to S3
        run: |
          aws s3 sync ./frontend/build s3://${{ secrets.S3_BUCKET }} --delete

      - name: Invalidate CloudFront (optional)
        if: ${{ secrets.CLOUDFRONT_ID != '' }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_ID }} \
            --paths '/*'
