name: Deploy Rcvo to S3
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AKIAV62Y2242JYAGVJ72 }}
          aws-secret-access-key: ${{ secrets.DoTbwIUb6g8pmdMW4krSX2kOSaVrTwxeyAgVWJlA }}
          aws-region: eu-west-3

      - name: Sync to S3 bucket
        run: |
          aws s3 sync . s3://rcvo-officiel --delete --region eu-west-3
