# .github/workflows/deploy-to-s3.yml
name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ASSISTANT_ROLE_ARN }}
          aws-region:    ${{ secrets.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci
        # Si vous n'avez pas de package-lock.json, remplacez par `npm install`

      - name: Build frontend
        run: npm run build
        # Adaptez si votre script ou dossier de sortie est différent (ex: `npm run build --prefix frontend`)

      - name: Sync to S3
        run: |
          aws s3 sync ./build s3://${{ secrets.S3_BUCKET }} --delete
        # Remplacez `./build` par le dossier généré (ex: `./dist`)

      - name: Invalidate CloudFront (optional)
        if: ${{ secrets.CLOUDFRONT_ID != '' }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_ID }} \
            --paths "/*"
