name: EB Ops Toolbox (Rcvo)

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: "Nom de l'environnement EB (ex: rcvo-backend-b / Rcvo-Backend-staging / Rcvo-UI-prod)"
        required: true
        default: rcvo-backend-b
      action:
        description: "Action à exécuter"
        required: true
        type: choice
        options: [get-health, restart-app, fetch-eb-logs]
      health_path:
        description: "Chemin healthcheck (si get-health)"
        required: false
        default: "/health"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-3

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Exécuter l'action demandée
        shell: bash
        run: |
          set -euo pipefail
          ENV="${{ inputs.env_name }}"
          ACTION="${{ inputs.action }}"
          HEALTH="${{ inputs.health_path }}"

          echo "Environnement: $ENV"
          echo "Action: $ACTION"

          case "$ACTION" in
            get-health)
              URL="http://$(aws elasticbeanstalk describe-environments \
                --environment-names "$ENV" \
                --query 'Environments[0].EndpointURL' --output text)"
              echo "Health URL: $URL$HEALTH"
              code=$(curl -sS -o /dev/null -w "%{http_code}" "$URL$HEALTH" || true)
              echo "HTTP $code"
              [ "$code" = "200" ] || exit 1
              ;;

            restart-app)
              aws elasticbeanstalk restart-app-server --environment-name "$ENV"
              echo "Redémarrage demandé."
              ;;

            fetch-eb-logs)
              aws elasticbeanstalk request-environment-info \
                --environment-name "$ENV" --info-type bundle
              sleep 20
              URL=$(aws elasticbeanstalk retrieve-environment-info \
                --environment-name "$ENV" --info-type bundle \
                --query 'EnvironmentInfo[-1].Message' --output text)
              echo "URL logs : $URL"
              curl -fSL "$URL" -o eb-logs.zip
              echo "📦 Logs téléchargés dans eb-logs.zip"
              ;;

            *)
              echo "Action inconnue"
              exit 2
              ;;
          esac
