name: EB Ops Toolbox

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: "EB EnvName (ex: rcvo-backend-b / Rcvo-Backend-staging / Rcvo-UI-prod)"
        required: true
      action:
        description: "Action"
        required: true
        type: choice
        options: [get-health, restart-app, fetch-eb-logs]
      health_path:
        description: "Path santé (get-health)"
        required: false
        default: "/health"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-3

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Execute
        shell: bash
        run: |
          set -euo pipefail
          ENV_NAME="${{ inputs.env_name }}"
          ACTION="${{ inputs.action }}"
          HEALTH="${{ inputs.health_path }}"

          case "$ACTION" in
            get-health)
              URL="http://$(aws elasticbeanstalk describe-environments --environment-names "$ENV_NAME" --query 'Environments[0].EndpointURL' --output text)"
              echo "Health URL: $URL$HEALTH"
              code=$(curl -sS -o /dev/null -w "%{http_code}" "$URL$HEALTH" || true)
              echo "HTTP: $code"
              [ "$code" = "200" ] || exit 1
              ;;

            restart-app)
              aws elasticbeanstalk restart-app-server --environment-name "$ENV_NAME"
              echo "Restart envoyé."
              ;;

            fetch-eb-logs)
              aws elasticbeanstalk request-environment-info --environment-name "$ENV_NAME" --info-type bundle
              sleep 20
              URL=$(aws elasticbeanstalk retrieve-environment-info --environment-name "$ENV_NAME" --info-type bundle --query 'EnvironmentInfo[-1].Message' --output text)
              echo "Bundle: $URL"
              curl -fSL "$URL" -o eb-logs.zip
              echo "eb-logs.zip téléchargé (tu peux le récupérer en artifact dans les logs du job)."
              ;;

            *) echo "Action inconnue"; exit 2 ;;
          esac
