name: EC2 Cleanup & Downsizing
on:
  schedule:
    - cron: '0 4 * * 1' # tous les lundis à 4h UTC
  workflow_dispatch:
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Stop instances inutiles
        run: |
          INSTANCES=$(aws ec2 describe-instances \
            --filters Name=instance-type,Values=t2.micro \
                      Name=instance-state-name,Values=running \
            --region "$AWS_REGION" \
            --query 'Reservations[].Instances[?Tags[?Key==`RcvoRole`]].InstanceId' --output text)
          for ID in $INSTANCES; do
            echo "⏹️ Arrêt de $ID"
            aws ec2 stop-instances --instance-ids "$ID" --region "$AWS_REGION"
          done
      - name: Change type si arrêté
        run: |
          STOPPED=$(aws ec2 describe-instances \
            --filters Name=instance-state-name,Values=stopped \
                      Name=instance-type,Values=t2.micro \
            --region "$AWS_REGION" \
            --query 'Reservations[].Instances[].InstanceId' --output text)
          for ID in $STOPPED; do
            echo "⚙️ Passage en t3.micro pour $ID"
            aws ec2 modify-instance-attribute --instance-id "$ID" --instance-type '{"Value":"t3.micro"}' --region "$AWS_REGION"
            aws ec2 start-instances --instance-ids "$ID" --region "$AWS_REGION"
          done
