name: Deploy Infrastructure

on:
  push:
    paths:
      - 'infrastructure/**'
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ASSISTANT_ROLE_ARN }}  # ou clés statiques si vous préférez secrets.AWS_ACCESS_KEY_ID etc.
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          cd infrastructure/instances
          terraform init

      - name: Terraform Plan
        run: |
          cd infrastructure/instances
          terraform plan -out=tfplan

      - name: Terraform Apply
        run: |
          cd infrastructure/instances
          terraform apply -auto-approve tfplan
