name: OIDC Smoke

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-3

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS creds (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: EB ping
        run: |
          aws elasticbeanstalk describe-environments \
            --region "$AWS_REGION" \
            --query 'Environments[].[ApplicationName,EnvironmentName,Health,Status]' \
            --output table
