name: Vehicle Categorization

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - 'qcm/categories.json'
      - '.github/workflows/vehicle-categorization.yml'

jobs:
  categorize:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # pour pouvoir commit/push le mapping
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # AUCUN npm, AUCUN docker, AUCUN terraform.
      # Sc
