name: Vehicle Categorization

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - '**/package.json'
      - '**/categories.json'
      - 'qcm/**'
      - 'src/vehicles/**'
      - 'scripts/**'
      - '.github/workflows/vehicle-categorization.yml'

jobs:
  categorize:
    name: Générer la table de correspondance
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # 1) Trouver un package.json qui déclare "build:mapping"
      - name: Localiser package.json avec script build:mapping
        id: find_pkg
        shell: bash
        run: |
          set -euo pipefail
          FOUND_DIR=""
          while IFS= read -r file; do
            if node -e "const fs=require('fs');const p='$file';const j=JSON.parse(fs.readFileSync(p,'utf8'));process.exit(j.scripts&&j.scripts['build:mapping']?0:1)"; then
              FOUND_DIR="$(dirname "$file")"
              echo "✔ Script build:mapping trouvé dans: $FOUND_DIR"
              break
            fi
          done < <(git ls-files '**/package.json' || true)
          if [ -n "$FOUND_DIR" ]; then
            echo "dir=$FOUND_DIR" >> "$GITHUB_OUTPUT"
            echo "found=true"     >> "$GITHUB_OUTPUT"
          else
            echo "found=false"    >> "$GITHUB_OUTPUT"
          fi

      # 2) Localiser le fichier catégories.json (où qu'il soit dans le repo)
      - name: Localiser fichier catégories
        id: find_cats
        shell: bash
        run: |
          set -euo pipefail
          # priorités de chemins usuels
          CANDIDATES=(
            "qcm/categories.json"
            "src/qcm/categories.json"
            "data/categories.json"
            "config/categories.json"
            "src/**/categories.json"
            "**/categories.json"
          )
          FOUND=""
          for pat in "${CANDIDATES[@]}"; do
            # liste les fichiers suivis par git correspondant au motif
            while IFS= read -r f; do
              # vérifie qu'il s'agit bien d'un JSON avec une clé "categories" (tableau)
              if node -e "const fs=require('fs');const p=process.argv[1];try{const j=JSON.parse(fs.readFileSync(p,'utf8'));if(Array.isArray(j.categories))process.exit(0);}catch{}process.exit(1)" "$f"; then
                FOUND="$f"; break 2
              fi
            done < <(git ls-files "$pat" || true)
          done

          if [ -n "$FOUND" ]; then
            echo "✔ Fichier catégories trouvé: $FOUND"
            echo "path=$FOUND" >> "$GITHUB_OUTPUT"
          else
            echo "❌ Aucun fichier catégories.json valide trouvé."
            echo "Liste rapide des *.json à la racine :" 
            ls -1 *.json 2>/dev/null || true
            exit 2
          fi

      # 3A) Si build:mapping existe → exécuter npm dans ce dossier
      - name: Installer dépendances (safe)
        if: ${{ steps.find_pkg.outputs.found == 'true' }}
        working-directory: ${{ steps.find_pkg.outputs.dir }}
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            npm ci --no-audit --no-fund
          else
            npm i  --no-audit --no-fund
          fi

      - name: Générer le mapping (npm run build:mapping)
        if: ${{ steps.find_pkg.outputs.found == 'true' }}
        working-directory: ${{ steps.find_pkg.outputs.dir }}
        env:
          RCVO_CATEGORIES_FILE: ${{ steps.find_cats.outputs.path }}
        run: |
          # si ton script lit un chemin via variable env, il peut utiliser RCVO_CATEGORIES_FILE
          npm run build:mapping --silent

      # 3B) Sinon → fallback sans npm : copier/valider vers src/vehicles/mapping.json
      - name: Générer le mapping (fallback sans npm)
        if: ${{ steps.find_pkg.outputs.found != 'true' }}
        env:
          CATS_FILE: ${{ steps.find_cats.outputs.path }}
        run: |
          set -euo pipefail
          OUT="src/vehicles/mapping.json"
          mkdir -p "$(dirname "$OUT")"
          node - <<'JS' "$CATS_FILE" "$OUT"
          import fs from 'fs';
          const catsPath = process.argv[2], outPath = process.argv[3];
          let spec;
          try { spec = JSON.parse(fs.readFileSync(catsPath,'utf8')); }
          catch(e){ console.error(`❌ JSON invalide dans ${catsPath}: ${e.message}`); process.exit(2); }
          if (!Array.isArray(spec.categories)) { console.error("❌ Attendu: { categories:[{name,models[]},...], default? }"); process.exit(2); }
          for (const c of spec.categories) {
            if (typeof c.name!=='string' || !Array.isArray(c.models)) {
              console.error("❌ Chaque catégorie: {name:string, models:string[]}"); process.exit(2);
            }
          }
          fs.writeFileSync(outPath, JSON.stringify(spec, null, 2));
          console.log(`✅ mapping écrit -> ${outPath}`);
          JS

      # 4) Commit uniquement si ça a changé
      - name: Commit & push mapping (si modifié)
        run: |
          FILE="src/vehicles/mapping.json"
          if [ ! -f "$FILE" ]; then
            echo "❌ Fichier attendu non trouvé: $FILE"; exit 2;
          fi
          if git diff --quiet --exit-code -- "$FILE"; then
            echo "ℹ️ Aucun changement dans $FILE, rien à committer."
            exit 0
          fi
          git config user.name  "github-actions"
          git config user.email "actions@github.com"
          git add "$FILE"
          git commit -m "[skip ci] 🔄 Mise à jour du mapping véhicules"
          git push
